spring:
  application:
    name: eureka-server

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true