spring:
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: refresh, bean, health, prometheus, info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8888